    executable              = EGamma_Run2018A2018_script.sh
    arguments               = $(ProcId)

    should_transfer_files   = YES
    transfer_input_files    = /ceph/cms/store/user/yxiang/Condor_Preselection/input/Filelist/Filelist_EGamma_Run2018A2018_$(ProcId).list, /ceph/cms/store/user/yxiang/Condor_Preselection/input/AnalysisFile.tar.gz
    output                  = /ceph/cms/store/user/yxiang/Condor_Preselection/output_May_02_09_50/OUT_EGamma_Run2018A2018_May_02_09_50.$(ProcId).out
    error                   = /ceph/cms/store/user/yxiang/Condor_Preselection/error_May_02_09_50/ERR_EGamma_Run2018A2018_May_02_09_50.$(ProcId).err
    log                     = /ceph/cms/store/user/yxiang/Condor_Preselection/log_May_02_09_50/LOG_EGamma_Run2018A2018_May_02_09_50.$(ProcId).log

    x509userproxy           = /tmp/x509up_u31705
    RequestMemory           = 2048
    RequestCpus             = 1

    +SingularityImage       = "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel6-m202006"

    +DESIRED_Sites          = "T2_US_UCSD" 

    queue 76
